//! 3Dmigoto (SRMI) 核心套件内置初始化与云端同步模块

use crate::error::{LiquiModError, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// 默认内置的标准 d3dx.ini 模板文本
pub const EMBEDDED_D3DX_INI_TEMPLATE: &str = r#"; 3Dmigoto for Honkai: Star Rail (SRMI) Configuration File
; Generated by LiquiMod

[Loader]
target = StarRail.exe
module = d3d11.dll
require_admin = false
delay = 0

[Hunting]
hunting = 0
marking_actions = clipboard

[Logging]
calls = 0
debug = 0
show_warnings = 0

[Rendering]
track_texture_updates = 0
track_region_hashes = 0
track_implicit_index_buffers = 1
allow_buffer_resize = 1

[Constants]
; Global constants for mod variables
"#;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MigotoReleaseInfo {
    pub tag_name: String,
    pub name: String,
    pub body: String,
    pub published_at: Option<String>,
    pub download_url: Option<String>,
    pub asset_name: Option<String>,
    pub size_bytes: Option<u64>,
}

/// 在指定的目标目录下初始化 3Dmigoto 工作区
pub fn init_migoto_workspace(target_dir: &Path) -> Result<PathBuf> {
    if !target_dir.exists() {
        std::fs::create_dir_all(target_dir)?;
    }

    let mods_dir = target_dir.join("Mods");
    if !mods_dir.exists() {
        std::fs::create_dir_all(&mods_dir)?;
    }

    let shader_fixes_dir = target_dir.join("ShaderFixes");
    if !shader_fixes_dir.exists() {
        std::fs::create_dir_all(&shader_fixes_dir)?;
    }

    let ini_path = target_dir.join("d3dx.ini");
    if !ini_path.exists() {
        std::fs::write(&ini_path, EMBEDDED_D3DX_INI_TEMPLATE)?;
    }

    Ok(ini_path)
}

/// 检查目标目录是否已经是合法的 3Dmigoto 工作区
pub fn is_migoto_workspace(target_dir: &Path) -> bool {
    if !target_dir.is_dir() {
        return false;
    }
    target_dir.join("d3dx.ini").is_file()
}

/// 获取 SRMI 最新的 Release 版本信息（支持 GitHub 直连、代理及国内镜像加速）
pub async fn check_latest_srmi_release(
    github_token: Option<&str>,
    mirror_url: Option<&str>,
) -> Result<MigotoReleaseInfo> {
    let base_api = if let Some(mirror) = mirror_url {
        let clean = mirror.trim_end_matches('/');
        format!(
            "{}/https://api.github.com/repos/SpectrumQT/SRMI-Package/releases/latest",
            clean
        )
    } else {
        "https://api.github.com/repos/SpectrumQT/SRMI-Package/releases/latest".to_string()
    };

    let client = reqwest::Client::builder()
        .user_agent("LiquiMod-Client")
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| LiquiModError::Io(std::io::Error::other(e.to_string())))?;

    let mut req = client.get(&base_api);
    if let Some(token) = github_token {
        if !token.trim().is_empty() {
            req = req.header("Authorization", format!("token {}", token.trim()));
        }
    }

    let res = req.send().await.map_err(|e| {
        LiquiModError::Io(std::io::Error::other(format!(
            "检查 3DMigoto 更新失败: {}",
            e
        )))
    })?;

    if !res.status().is_success() {
        return Err(LiquiModError::Io(std::io::Error::other(format!(
            "GitHub API 响应错误状态码: {}",
            res.status()
        ))));
    }

    let json: serde_json::Value = res.json().await.map_err(|e| {
        LiquiModError::Io(std::io::Error::other(format!(
            "解析 Release JSON 失败: {}",
            e
        )))
    })?;

    let tag_name = json["tag_name"].as_str().unwrap_or("").to_string();
    let name = json["name"].as_str().unwrap_or(&tag_name).to_string();
    let body = json["body"].as_str().unwrap_or("").to_string();
    let published_at = json["published_at"].as_str().map(|s| s.to_string());

    let mut download_url = None;
    let mut asset_name = None;
    let mut size_bytes = None;

    if let Some(assets) = json["assets"].as_array() {
        for asset in assets {
            if let Some(a_name) = asset["name"].as_str() {
                if a_name.ends_with(".zip") {
                    asset_name = Some(a_name.to_string());
                    download_url = asset["browser_download_url"]
                        .as_str()
                        .map(|s| s.to_string());
                    size_bytes = asset["size"].as_u64();
                    break;
                }
            }
        }
    }

    Ok(MigotoReleaseInfo {
        tag_name,
        name,
        body,
        published_at,
        download_url,
        asset_name,
        size_bytes,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_init_migoto_workspace() {
        let temp = tempfile::tempdir().unwrap();
        let target = temp.path().join("SRMI");

        assert!(!is_migoto_workspace(&target));
        let ini = init_migoto_workspace(&target).unwrap();
        assert!(ini.is_file());
        assert!(is_migoto_workspace(&target));
        assert!(target.join("Mods").is_dir());
        assert!(target.join("ShaderFixes").is_dir());

        let content = std::fs::read_to_string(&ini).unwrap();
        assert!(content.contains("[Loader]"));
        assert!(content.contains("target = StarRail.exe"));
    }
}
